### ISSUE TITLE
Checklist to get it functioning

### ISSUE THREAD

**Issue by aurtzy** [aurtzy/linux-autosetup#1]
- [x] Figure out method of reading a config file.

Backup capability:

- [x] #5
- [x] #10 (discontinued)

Installation capability:

- [x] #3
- [x] 'recovery': Import backed up archives to directories specified in config (discontinued)

Interaction capability:

- [x] note to-do first: rename 'recovery' stuff to 'archive'
- [x] #17
